

version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
      - API_KEY=${API_KEY}
    volumes:
      - .:/app